// Lista completa de 232 perguntas do YSQ-L3 (Forma Longa)
export const ysqQuestions: string[] = [
  "As pessoas não conseguiram satisfazer as minhas necessidades emocionais.",
  "Eu não recebi suficiente amor e atenção.",
  "De modo geral, não tenho tido ninguém para me dar conselhos e apoio emocional.",
  "A maior parte do tempo, não tenho tido ninguém para me dar carinho, compartilhar sua presença comigo ou se importar profundamente com o que me acontece.",
  "Eu não tive ninguém que quisesse ser mais íntimo e passar bastante tempo comigo em grande parte da minha vida.",
  "Em geral não havia pessoas para me dar carinho, segurança, apoio e afeição.",
  "Eu não senti que era especial para alguém, durante grande parte da minha vida.",
  "Em geral não tenho ninguém que realmente me escute, me compreenda ou esteja sintonizado com as minhas verdadeiras necessidades e sentimentos.",
  "Eu raramente tenho alguma pessoa forte para me dar bons conselhos ou orientação quando não tenho certeza do que fazer.",
  "Eu me preocupo com a possibilidade de as pessoas que amo morrerem em breve, mesmo que haja poucas razões médicas para confirmar minhas preocupações.",
  "Percebo que me agarro às pessoas com as quais tenho intimidade por ter medo que elas me deixem.",
  "Eu me preocupo com a possibilidade de as pessoas das quais sou próximo, me deixarem ou me abandonarem.",
  "Sinto que me falta uma base estável de apoio emocional.",
  "Não sinto que os relacionamentos importantes irão durar, acredito que eles vão terminar.",
  "Sinto que sou apegado a parceiros/as que não são capazes de se comprometerem comigo.",
  "No final, acabarei só.",
  "Quando sinto que alguém com que me importo está se afastando, fico desesperado(a).",
  "Às vezes, me preocupo tanto de que as pessoas me deixem, que acabo fazendo com que se afastem.",
  "Fico incomodado quando alguém me deixa sozinho/a mesmo que por pouco tempo.",
  "Não posso contar com as pessoas que me apoiam estejam sempre disponíveis para me ajudar em uma base regular.",
  "Não posso me permitir ficar realmente íntimo de outras pessoas, porque não posso ter certeza de que poderei contar sempre com elas.",
  "Parece que as pessoas importantes da minha vida estão sempre indo e vindo.",
  "Preocupo-me muito que as pessoas que eu amo encontrem alguém que vão preferir e me deixem.",
  "As pessoas que me são próximas têm sido muito imprevisíveis; ora são legais e disponíveis, ora estão zangadas, chateadas, absorvidas em si mesmas, brigando e assim por diante.",
  "Preciso tanto das pessoas que tenho medo de perdê-las.",
  "Não posso ser eu mesma/o ou expressar o que realmente sinto, pois as pessoas me abandonariam.",
  "Sinto que as pessoas irão tirar vantagem de mim.",
  "Frequentemente sinto que tenho de me proteger dos outros.",
  "Sinto que não posso baixar a guarda na presença de outros pois eles me prejudicariam intencionalmente.",
  "Se uma pessoa é legal comigo, presumo que ela esta querendo alguma coisa.",
  "É só uma questão de tempo antes que alguém me traia.",
  "A maioria das pessoas só pensa em si mesmas.",
  "Tenho uma grande dificuldade em confiar nas pessoas.",
  "Desconfio muito dos motivos dos outros.",
  "As pessoas raramente são honestas; elas geralmente não são o que parecem.",
  "Eu geralmente fico procurando os motivos ocultos das pessoas.",
  "Se acho que alguém quer me prejudicar, tento prejudica-lo/a primeiro.",
  "As pessoas geralmente têm de me provar que são dignas antes que eu consiga confiar nelas.",
  "Tenho muito medo de ser traído pelas pessoas.",
  "Invento “testes” para as pessoas para ver se elas estão me dizendo a verdade e se são bem intencionadas.",
  "Acredito no ditado “Quem não controla é controlado”.",
  "Fico com raiva quando penso como fui maltratado/a por outras pessoas durante toda a minha vida.",
  "Fui abusada/o fisicamente, emocionalmente ou sexualmente por pessoas importantes na minha vida.",
  "Eu não me encaixo.",
  "Sou fundamentalmente diferente das outras pessoas.",
  "Eu não pertenço a nenhum grupo; sou um/a solitário/a.",
  "Sinto-me alienado/a das outras pessoas.",
  "Sinto-me isolado/a e sozinho/a.",
  "Sempre me sinto excluído/a dos grupos.",
  "Ninguém me entende realmente.",
  "A minha família sempre foi diferente das famílias que nos cercavam.",
  "Às vezes, sinto como se eu fosse um/a alienígena.",
  "Se eu desaparecesse amanhã, ninguém perceberia.",
  "Nenhum/a homem/mulher que eu desejar vai me amar depois de saber dos meus defeitos.",
  "Ninguém que eu desejar vai querer ficar perto de mim depois de conhecer o meu verdadeiro eu.",
  "Sou inerentemente defeituoso/a e cheio/a de falhas.",
  "Por mais que eu tente, sinto que não conseguirei ser um/a homem/mulher significativo/a me respeite ou sinta que eu tenho valor.",
  "Sou indigna/o do amor, da atenção e do respeito dos outros.",
  "Sinto que não mereço ser amado/a.",
  "Sou inaceitável demais, de todas as maneiras possíveis, para me revelar aos outros.",
  "Se as pessoas descobrissem meus principais defeitos, eu não conseguiria encará-las.",
  "Quando as pessoas gostam de mim, sinto que as estou enganando.",
  "Frequentemente, sou atraído/a por pessoas que são muito criticas (a mim) ou me rejeitam.",
  "Tenho segredos que não quero que as pessoas próximas a mim descubram.",
  "É minha culpa que meus pais não conseguiram se amar o suficiente.",
  "Não deixo que as pessoas conheçam meu verdadeiro eu.",
  "Um dos meus maiores medos é que meus defeitos sejam expostos.",
  "Não consigo entender como alguém pode me amar.",
  "Quasi nada que faço no trabalho (ou na escola) é tão bom quanto o que os outros fazem.",
  "Sou incompetente no que se refere as realizações.",
  "A maioria das pessoas é mais capaz do eu em áreas profissionais (ou escolares) e em suas realizações.",
  "Eu sou um fracasso.",
  "Não tenho talento quanto a maioria das pessoas tem em sua profissão (ou no estudo).",
  "Não sou tão inteligente quanto a maioria das pessoas no que se refere a trabalho (ou estudo).",
  "Sinto-me humilhada/o por meus fracassos e inadequações na esfera do trabalho (ou estudo).",
  "Frequentemente me sinto embaraçada/o perto de outras pessoas porque não estou à altura delas em termos de realizações.",
  "Muitas vezes comparo minhas realizações com as de outras pessoas e sinto que elas são muito mais bem-sucedidas.",
  "Não me sinto capaz de me arranjar sozinho/a no dia-a-dia.",
  "Preciso que as outras pessoas me ajudem a fazer as coisas.",
  "Não me sinto capaz de lidar bem as situações sozinho/a.",
  "Acredito que as pessoas conseguem cuidar de mim melhor do que eu mesmo/a.",
  "Tenho dificuldade em lidar com as tarefas novas fora do trabalho, a menos que tenha alguém para me orientar.",
  "Penso em mim como uma pessoa dependente, no que se refere a funcionamento cotidiano.",
  "Acabo estragando tudo o que tento fazer, mesmo fora do trabalho (ou da escola).",
  "Sou incapaz em quase todas as áreas da vida.",
  "Se eu confiar no meu próprio julgamento nas situações do dia-a-dia, tomarei a decisão errada.",
  "Falta-me bom senso.",
  "Não se pode confiar em meu julgamento nas situações do dia-a-dia.",
  "Não me sinto confiante em minhas habilidades para resolver os problemas que surgem no dia-a-dia.",
  "Sinto que preciso de alguém em que eu possa confiar para me dar conselhos sobre questões práticas.",
  "Sinto-me mais como uma criança do que como um adulto quando é preciso assumir responsabilidades no dia-a-dia.",
  "Acho as responsabilidades do dia-a-dia esmagadoras.",
  "Não consigo me livrar da sensação de que algo ruim vai acontecer.",
  "Sinto que algum desastre (natural, criminal, financeiro ou médico) vai acontecer a qualquer momento.",
  "Tenho medo de me tornar um/a sem-teto ou um/a mendigo/a.",
  "Tenho medo de ser atacada/o.",
  "Tomo muitas precauções para não adoecer e nem me machucar.",
  "Tenho medo de pegar uma doença grave, mesmo que de nada sério tenha sido diagnosticado por um médico.",
  "Sou uma pessoa medrosa.",
  "Eu me preocupo muito com todas as coisas horríveis que acontecem no mundo: criminalidade, poluição e etc.",
  "Muitas vezes, acho que posso enlouquecer.",
  "Sinto, frequentemente, que vou ter um ataque de ansiedade.",
  "Tenho muito medo de ter um ataque cardíaco, embora haja poucas razões médicas que justifiquem minha preocupação.",
  "Sinto que o mundo é um lugar perigoso.",
  "Não consegui me separar de meu pai/mãe, ou de ambos, assim como as outras pessoas da minha idade parecem conseguir.",
  "Meu pai/mãe, ou ambos, e eu tendemos a nos envolver excessivamente com a vida e com os problemas uns dos outros.",
  "É muito difícil para meu pai/mãe, ou ambos, e eu escondermos detalhes íntimos uns dos outros sem nos sentirmos traídos ou culpados.",
  "Meu pai/mãe, ou ambos, temos que nos falar quase todos os dias, ou um de nós se sente culpado, magoado, desapontado ou sozinho.",
  "Muitas vezes, sinto que não tenho uma identidade separada da de meus pais ou de meu parceiro/a.",
  "Muitas vezes me parece que meus pais estão vivendo através de mim – eu não tenho uma vida própria.",
  "É muito difícil para mim manter alguma distância das pessoas de quem sou intimo/a; não é fácil para mim ter um senso separado de mim mesmo/a.",
  "Estou tão envolvido/a com meu/minha parceiro/a ou com meus pais que não sei realmente quem sou, ou o que quero.",
  "Tenho dificuldade em separar o meu ponto de vista, ou opinião, dos de meus pais ou parceiro/a.",
  "Sinto que não tenho nenhuma privacidade no que se refere aos meus pais ou parceiro/a.",
  "Sinto que meus pais estão, ou ficariam, muito magoados por eu morar sozinho/a, longe deles.",
  "Deixo as pessoas fazerem as coisas do jeito delas porque tenho medo das consequências.",
  "Acho que se eu fizer o que quero, só vou arranjar problemas.",
  "Sinto que não tenho escolha além de ceder aos desejos das pessoas, ou elas vão me rejeitar ou me retaliar de alguma maneira.",
  "Nos meus relacionamentos, deixo a outra pessoa assumir o controle.",
  "Sempre deixei os outros escolherem por mim, de modo que não sei realmente o que quero para mim.",
  "Sinto que as maiores decisões da minha vida não foram realmente minhas.",
  "Eu me preocupo muito em agradar os outros para que eles não me rejeitem.",
  "Tenho grande dificuldade em exigir que meus direitos sejam respeitados e que meus sentimentos sejam levados em conta.",
  "Eu me vingo das pessoas de maneira sutil, em vez de demonstrar minha raiva de forma direta.",
  "Vou muito além do que a maioria das pessoas para evitar confrontações.",
  "Coloco as necessidades dos outros antes das minhas, ou me sinto culpada/o.",
  "Sinto-me culpado/a quando desaponto as pessoas.",
  "Dou mais às pessoas do que recebo delas.",
  "Sou aquela/e que geralmente acaba cuidando das pessoas de quem sou próxima/o.",
  "Não há praticamente nada que eu não possa aceitar quando amo alguém.",
  "Sou uma boa pessoa, pois penso nos outros mais do que em mim mesma/o.",
  "No trabalho, normalmente sou aquela/o que se apresenta como voluntária/o para fazer tarefas extras, ou trabalhar mais tempo.",
  "Por mais ocupada/o que esteja, eu sempre arranjo tempo para os outros.",
  "Consigo me virar com muito pouco, porque as minhas necessidades são mínimas.",
  "Só me sinto feliz quando aqueles que me cercam estão felizes.",
  "Fico tão ocupada/o fazendo coisas para as pessoas de quem gosto que tenho muito pouco tempo para mim.",
  "Sempre fui aquela/e que escuta os problemas de todo o mundo.",
  "Fico mais à vontade dando um presente do que recebendo.",
  "As pessoas me vêem como alguém que faz demais pelos outros e pouco por si mesmo.",
  "Não importa quanto eu dê, sinto que nunca é o suficiente.",
  "Se faço o que quero, me sinto muito desconfortável.",
  "É muito difícil para mim pedir aos outros que atendam às minhas necessidades.",
  "Tenho medo de perder o controle de minhas ações.",
  "Tenho medo de machucar seriamente alguém, física ou emocionalmente, caso perca o controle de minha raiva.",
  "Sinto que preciso controlar as minhas emoções e impulsos, ou algo de ruim pode vir a acontecer.",
  "Dentro de mim há muita raiva e ressentimento que eu não expresso.",
  "Tenho muita vergonha em demonstrar sentimentos positivos em relação aos outros (por exemplo, afeição, demonstrações de carinho).",
  "Acho embaraçoso expressar meus sentimentos para os outros.",
  "Tenho dificuldade em ser carinhosa/o e espontânea/o.",
  "Eu me controlo tanto que as pessoas acham que não tenho emoções.",
  "As pessoas me vêem como emocionalmente contida/o.",
  "Preciso ser a/o melhor em tudo o que faço; não consigo aceitar vir em segundo lugar.",
  "Esforço-me para manter quase tudo em perfeita ordem.",
  "Preciso causar a melhor impressão, praticamente o tempo todo.",
  "Tento fazer o melhor; não consigo aceitar o “suficientemente bom”.",
  "Tenho tantas coisas para fazer que quase não me sobra tempo para relaxar.",
  "Quase nada é bom o bastante; sempre posso fazer melhor.",
  "Preciso cumprir todas as minhas responsabilidades.",
  "Sinto que existe uma pressão constante sobre mim para conquistar e fazer coisas.",
  "Meus relacionamentos são prejudicados porque exijo demais de mim.",
  "Minha saúde é prejudicada porque me pressiono demais para me sair bem.",
  "Muitas vezes eu sacrifico prazer e felicidade para estar à altura dos meus padrões.",
  "Se cometo um erro, mereço ser muito criticado.",
  "Não consigo me soltar ou me desculpar por meus erros com facilidade.",
  "Sou uma pessoa muito competitiva.",
  "Dou muito valor a dinheiro e status.",
  "Tenho que ser sempre o/a “Número Um” em termos de desempenho.",
  "Tenho muita dificuldade em aceitar um “não” como resposta quando quero alguma coisa de alguém.",
  "Geralmente me zango, ou me irrito quando não consigo aquilo que quero.",
  "Sou especial e não deveria ter que aceitar muitas das restrições impostas às outras pessoas.",
  "Detesto ser coagido/a ou impedida/o de fazer o que quero.",
  "Acho que não deveria ter que obedecer às regras e convenções normais assim como os outros.",
  "Sinto que aquilo que tenho a oferecer é muito mais valioso do que as contribuições dos outros.",
  "Geralmente coloco as minhas necessidades acima das necessidades dos outros.",
  "Muitas vezes sinto que estou tão envolvida/o com minhas prioridades que não tenho tempo para os amigos ou a família.",
  "As pessoas frequentemente me dizem que sou muito controlador/a em relação a como as coisas devem ser feitas.",
  "Fico muito irritada/o quando as pessoas não fazem o que eu lhes peço.",
  "Não tolero que as pessoas me digam o que fazer.",
  "Tenho grande dificuldade para deixar de beber, fumar, comer demais e modificar outros comportamentos problemáticos.",
  "Parece que não consigo me disciplinar e levar até o fim tarefas rotineiras ou chatas.",
  "Muitas vezes, me permito seguir impulsos e expressar emoções que me trazem problemas ou machucam as pessoas.",
  "Quando não consigo atingir algum objetivo, fico facilmente frustrada/o e desisto.",
  "Para mim é muito difícil sacrificar uma gratificação imediata para atingir um objetivo a longo prazo.",
  "Frequentemente, depois que fico com raiva, não consigo mais me controlar.",
  "Tendo a exagerar em muitas coisas, mesmo sabendo que elas são ruins para mim.",
  "Eu me aborreço muito facilmente.",
  "Quando as tarefas ficam difíceis, geralmente não consigo perseverar e concluí-las.",
  "Não consigo me concentrar em nada por muito tempo.",
  "Não consigo me obrigar a fazer as coisas de que não gosto, mesmo sabendo que é para o meu próprio bem.",
  "Perco a calma diante da ofensa mais insignificante.",
  "Raramente consigo cumprir minhas resoluções.",
  "Quase nunca deixo de mostrar às pessoas o que realmente sinto, seja qual for o custo disso.",
  "Frequentemente faço por impulso coisas das quais me arrependo mais tarde.",
  "É importante para mim que a maioria das pessoas que eu conheço goste de mim.",
  "Eu me transformo, dependendo das pessoas com quem estou, para que elas gostem mais de mim.",
  "Eu me esforço muito para me encaixar.",
  "Minha auto-estima é baseada principalmente sobre como as pessoas me vêem.",
  "Ter dinheiro e conhecer pessoas importantes me faz sentir uma pessoa de valor.",
  "Gasto muito tempo com a minha aparência física para que as pessoas me valorizem.",
  "Aquilo que consigo alcançar tem mais valor para mim se for algo que chame a atenção das outras pessoas.",
  "Estou tão focado em me encaixar que às vezes não sei quem sou.",
  "Tenho dificuldade em estabelecer as minhas próprias metas sem levar em conta como outros irão responder a minhas escolhas.",
  "Quando olho para as minhas decisões de vida, vejo que fiz a maioria delas tendo em mente a aprovação das outras pessoas.",
  "Mesmo quando eu não gosto de alguém, ainda assim quero que ele/ela goste de mim.",
  "A não ser que receba muita atenção dos outros, sinto-me menos importante.",
  "Quando faço uma intervenção em uma reunião ou quando sou apresentado em um grupo, espero obter reconhecimento e admiração.",
  "Receber muitos louvores e elogios dos outros me faz sentir como uma pessoa de valor.",
  "Mesmo quando as coisas parecem estar indo bem, sinto que isso é apenas temporário.",
  "Se algo de bom acontecer, fico preocupado/a que algo de ruim vai acontecer logo em seguida.",
  "Todo cuidado é pouco; quase sempre alguma coisa irá dar errado.",
  "Por mais duro que eu trabalhe, fico preocupado/a com a possibilidade de ficar na miséria em termos financeiros.",
  "Preocupo-me com a possibilidade de que uma decisão equivocada leve a um desastre.",
  "Muitas vezes fico obcecado em tomar decisões insignificantes, porque as consequências de cometer um erro parecem muito sérias.",
  "Sinto-me melhor pressupondo que as coisas não darão certo para mim pois dessa forma não me sentirei desapontado/a se as coisas derem errado.",
  "Concentro-me mais nos aspectos e eventos negativos da vida do que nos positivos.",
  "Tendo a ser pessimista.",
  "Pessoas que me são próximas me consideram uma pessoa muito preocupada.",
  "Se as pessoas se entusiasmam demais em relação a alguma coisa, eu fico em situação desconfortável e sinto que tenho que alertá-los sobre o que poderia dar errado.",
  "Se cometo um erro, mereço ser punido.",
  "Se eu não me esforçar ao máximo, devo esperar fracassar.",
  "Não há desculpa se cometo um erro.",
  "Pessoas que não se esforçam deveriam ser punidas de alguma forma.",
  "Na maioria das vezes eu não aceito as desculpas das outras pessoas. Elas não estão dispostas a assumir responsabilidades e sofrer as consequências.",
  "Se não faço o que me compete, mereço sofrer as consequências.",
  "Muitas vezes penso sobre os erros que cometo e sinto raiva de mim mesmo/a.",
  "Quando as pessoas fazem algo ruim, tenho dificuldade em aplicar a frase “Perdoe e Esqueça”.",
  "Eu guardo mágoas mesmo depois que alguém pediu desculpas.",
  "Fico irritado/a quando penso que alguém se livra das consequências de um erro muito facilmente.",
  "Fico irritado/a quando as pessoas arranjam desculpas para si mesmas e culpam outras pessoas por seus problemas.",
  "Não importa o motivo pelo qual cometi um erro; quando faço algo errado, eu devo pagar o preço.",
  "Eu me castigo muito por erros que cometi.",
  "Sou uma pessoa má que merece ser punida."
];

// Mapeamento dos índices de perguntas (0-based) para cada uma das siglas de esquema
export const ysqMapping: Record<string, number[]> = {
  pe: [0, 1, 2, 3, 4, 5, 6, 7, 8],
  ab: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
  da: [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
  is: [43, 44, 45, 46, 47, 48, 49, 50, 51, 52],
  dv: [53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67],
  fr: [68, 69, 70, 71, 72, 73, 74, 75, 76],
  de: [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91],
  vu: [92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103],
  em: [104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114],
  sb: [115, 116, 117, 118, 119, 120, 121, 122, 123, 124],
  as: [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141],
  ie: [142, 143, 144, 145, 146, 147, 148, 149, 150],
  pi: [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166],
  me: [167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177],
  ai: [178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192],
  ba: [193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206],
  np: [207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217],
  pu: [218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231]
};

export const ysqLabels: Record<string, string> = {
  pe: "Privação Emocional",
  ab: "Abandono / Instabilidade",
  da: "Desconfiança / Abuso",
  is: "Isolamento Social / Alienação",
  dv: "Defectividade / Vergonha",
  fr: "Fracasso",
  de: "Dependência / Incompetência",
  vu: "Vulnerabilidade ao Dano ou Doença",
  em: "Emaranhamento / Self Subdesenvolvido",
  sb: "Subjugação",
  as: "Autossacrifício",
  ie: "Inibição Emocional",
  pi: "Padrões Inflexíveis / Postura Crítica",
  me: "Merecimento / Grandiosidade",
  ai: "Autocontrole / Autodisciplina Insuficientes",
  ba: "Busca de Aprovação / Reconhecimento",
  np: "Negativismo / Pessimismo",
  pu: "Punibilidade"
};

// Mapeamento dos EIDs nos 5 Grandes Domínios
export const ysqDomains: Record<string, { label: string; EIDs: string[] }> = {
  d1: {
    label: "I. Desconexão e Rejeição",
    EIDs: ["pe", "ab", "da", "is", "dv"]
  },
  d2: {
    label: "II. Autonomia e Desempenho Prejudicados",
    EIDs: ["fr", "de", "vu", "em"]
  },
  d3: {
    label: "III. Limites Prejudicados",
    EIDs: ["me", "ai"]
  },
  d4: {
    label: "IV. Orientação para o Outro",
    EIDs: ["sb", "as", "ba"]
  },
  d5: {
    label: "V. Supervigilância e Inibição",
    EIDs: ["ie", "pi", "np", "pu"]
  }
};
