"""init

Revision ID: 5b5e39437f20
Revises: 
Create Date: 2026-06-02 14:04:31.030322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5e39437f20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termo_consentimento', schema=None) as batch_op:
        batch_op.drop_column('data_assinatura')
        batch_op.drop_column('assinado')
        batch_op.drop_column('ip_assinatura')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termo_consentimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_assinatura', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('assinado', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('data_assinatura', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
